### PR TITLE
Issue353

### PR DESCRIPTION
**Pull request by ieggel**
Fixes issue #353 

Changes in this pull request:

- Add affiliation field in db
- Add address field in db
- Add country field in db
- Add input fields for profile edit page
- Add display fields including new tab on profile show page

@seanfcarroll

### CODE REVIEW

**Comment by scarroll32** [comment]
@ieggel Thanks for the pull request! It's failing on CI which is weird as the code looks OK to me. I will try to review before I go on vacation.

**Comment by ieggel** [comment]
@seanfcarroll Indeed weird, as after fetching the latest master and merging it with my current issue branch, everything worked fine locally.

**Comment by scarroll32** [comment]
OK I have pulled the code and run the test suite. There are three failing errors:

```ruby
Failures:

  1) API key visibility API key not visible to public users
     Failure/Error: <% if current_participant.access_to_contact_info?(@participant) %>

     ActionView::Template::Error:
       undefined method `access_to_contact_info?' for nil:NilClass
     # ./app/views/participants/show.html.erb:27:in `_app_views_participants_show_html_erb__4605933303661721604_70270962748580'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `access_to_contact_info?' for nil:NilClass
     #   ./app/views/participants/show.html.erb:27:in `_app_views_participants_show_html_erb__4605933303661721604_70270962748580'

  2) Email field visibility API key not visible to public users
     Failure/Error: <% if current_participant.access_to_contact_info?(@participant) %>

     ActionView::Template::Error:
       undefined method `access_to_contact_info?' for nil:NilClass
     # ./app/views/participants/show.html.erb:27:in `_app_views_participants_show_html_erb__4605933303661721604_70270964706300'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `access_to_contact_info?' for nil:NilClass
     #   ./app/views/participants/show.html.erb:27:in `_app_views_participants_show_html_erb__4605933303661721604_70270964706300'

  3) Participant fields should respond to #location
     Failure/Error: it { is_expected.to respond_to :location }
       expected #<Participant id: nil, email: "", admin: false, verified: false, verification_date: nil, timezone: ni...ttm: nil, slug: nil, api_key: nil, image_file: nil, affiliation: nil, country_cd: nil, address: nil> to respond to :location
     # ./spec/models/participant_spec.rb:19:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:62:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:61:in `block (2 levels) in <top (required)>'
```

The third one is easy: the location field was removed but the test code needs to be updated. I will do a commit for this.

The first and second are the same error, and a little more subtle. The ```access_to_contact_info?``` method is on the Participant model, which is fine. Rails creates an instance of the currently logged in participant's details in 'current_participant'. But if the participant is not logged in, this is nil, and so there cannot be a method against it.

Usually you would first check if it is not nil, eg like this:

```
 <% if current_participant && current_participant.access_to_contact_info?(@participant) %>
```

In the case of crowdAI however, we are using an authorization library called [Pundit](https://github.com/elabs/pundit), so I will refactor this code to keep the auth in a Pundit class. Also, we need to check if the user is an organizer AND they are a CLEF organizer, so I will add this.

Great first PR @ieggel !!

**Comment by ieggel** [comment]
@seanfcarroll 
OK, i clearly did not consider the case when a participant is not logged in. Thanks for pointing out. I will have a look at the fixed code as soon as it's up. Thanks.

**Pull request merged**
